name: "PR"

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Docker meta ci
      id: docker_meta_ci
      uses: crazy-max/ghaction-docker-meta@v3
      with:
        images: solidnerd/teamspeak-dev
        tag-sha: true
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push Dev
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ steps.docker_meta_ci.outputs.tags }}
        labels: ${{ steps.docker_meta_ci.outputs.labels }}
        cache-from: type=registry,ref=solidnerd/teamspeak-dev:master
        cache-to: type=inline
        outputs: type=docker,dest=/tmp/image-teamspeak.tar
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: image-teamspeak
        path: /tmp/image-teamspeak.tar
        if-no-files-found: warn
  e2e:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: image-teamspeak
        path: /tmp
        if-no-files-found: warn
    - name: Load Docker image
      run: |
        docker load --input /tmp/image-teamspeak.tar
        docker image ls -a
    - name: Execute End-to-End Test
      run: make e2e
